package org.piruntha.model;

public enum JobTitle {
    TRAINEE_SOFTWARE_ENGINEER,
    ASSOCIATE_SOFTWARE_ENGINEER,
    SOFTWARE_ENGINEER,
    SENIOR_SOFTWARE_ENGINEER,
    TECH_LEAD,
    PROJECT_MANAGER
}
